export const practitioner = {
  'count': 1,
  'next': null,
  'previous': null,
  'results': [{
    'id': 1,
    'profile': {
      'services': [{
        'id': 9,
        'hours': {
          'id': 1,
          'title': '8-5 Mon-Fri',
          'appointment_length': 60,
          'mon': '06:00-19:00',
          'tues': '06:00-19:00',
          'wed': '06:00-19:00',
          'thurs': '06:00-19:00',
          'fri': '',
          'sat': '',
          'sun': '',
          'default_hours': true,
          'timezone': 'Africa/Johannesburg'
        },
        'address': {
          'id': 2,
          'name': 'AppointmentGuru HQ',
          'latitude': '-26.13496000000000000000',
          'longitude': '28.02276000000006200000',
          'place_id': 'ChIJ2f9wDKEMlR4R4XoEgU84H8c',
          'address': '64 2nd Ave, Randburg, 2193, South Africa',
          'suburb': '',
          'city': '',
          'country': 'ZA',
          'phone': null,
          'email': '',
          'place_data': {
            'lng': '28.022760000000062',
            'vicinity': 'Parkhurst',
            'utc_offset': '120',
            'reference': 'CmRbAAAAaQg2cBLuMlTfR2CR5rQQ2b3-ji-tbBW0H_YX2NzvP-8LnFj222pEKlpDZ0UjP9UOG36WBee9y-cL1LJ40K8jYnDSE6vLkZl81LJZ-sNvfRiIzrtgWcOSU_rY9uk-Uo2sEhD9S-2WiV5SLdwZmehYboVPGhS8hUHsz-R3h4oG4dKmdo3yl8eEBA',
            'name': 'AppointmentGuru HQ',
            'id': '5fc60bd92591dd8dbbae01fed0ffe0fb2da1c87f',
            'addressId': '2',
            'html_attributions': '[]',
            'scope': 'GOOGLE',
            'place_id': 'ChIJ2f9wDKEMlR4R4XoEgU84H8c',
            'formatted_address': '64 2nd Ave, Randburg, 2193, South Africa',
            'lat': '-26.13496',
            'url': 'https://maps.google.com/?q=64+2nd+Ave,+Randburg,+2193,+South+Africa&ftid=0x1e950ca10c70ffd9:0xc71f384f81047ae1',
            'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png'
          }
        },
        'products': [{
          'id': 16,
          'title': 'AppointmentGuru demo',
          'description': null,
          'notes': null,
          'duration': 30,
          'currency': 'ZAR',
          'price': '0.00',
          'booking_notice_in_minutes': 1440,
          'reschedule_notice_in_minutes': 1440,
          'number_of_people': 1,
          'service': 9
        }]
      }, {
        'id': 31,
        'hours': {
          'id': 34,
          'title': '8-5 Mon-Fri',
          'appointment_length': 60,
          'mon': '',
          'tues': '',
          'wed': '',
          'thurs': '',
          'fri': '08:00-18:00',
          'sat': '',
          'sun': '',
          'default_hours': true,
          'timezone': 'Africa/Johannesburg'
        },
        'address': {
          'id': 30,
          'name': 'DBS Technologies',
          'latitude': '-26.13496000000000000000',
          'longitude': '28.02276000000006200000',
          'place_id': 'ChIJ2f9wDKEMlR4R4XoEgU84H8c',
          'address': '64 2nd Ave, Randburg, 2193, South Africa',
          'suburb': '',
          'city': '',
          'country': 'ZA',
          'phone': null,
          'email': '',
          'place_data': {
            'lng': '28.022760000000062',
            'vicinity': 'Parkhurst',
            'utc_offset': '120',
            'reference': 'CmRbAAAAaQg2cBLuMlTfR2CR5rQQ2b3-ji-tbBW0H_YX2NzvP-8LnFj222pEKlpDZ0UjP9UOG36WBee9y-cL1LJ40K8jYnDSE6vLkZl81LJZ-sNvfRiIzrtgWcOSU_rY9uk-Uo2sEhD9S-2WiV5SLdwZmehYboVPGhS8hUHsz-R3h4oG4dKmdo3yl8eEBA',
            'name': 'DBS Technologies',
            'id': '5fc60bd92591dd8dbbae01fed0ffe0fb2da1c87f',
            'addressId': '30',
            'html_attributions': '[]',
            'scope': 'GOOGLE',
            'place_id': 'ChIJ2f9wDKEMlR4R4XoEgU84H8c',
            'formatted_address': '64 2nd Ave, Randburg, 2193, South Africa',
            'lat': '-26.13496',
            'url': 'https://maps.google.com/?q=64+2nd+Ave,+Randburg,+2193,+South+Africa&ftid=0x1e950ca10c70ffd9:0xc71f384f81047ae1',
            'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png'
          }
        },
        'products': [{
          'id': 61,
          'title': 'VusJS for Professionals',
          'description': null,
          'notes': null,
          'duration': 300,
          'currency': 'ZAR',
          'price': '4000.00',
          'booking_notice_in_minutes': 1440,
          'reschedule_notice_in_minutes': 1440,
          'number_of_people': 1,
          'service': 31
        }, {
          'id': 62,
          'title': 'Building APIs with Python, Django and Django Rest Framework',
          'description': null,
          'notes': null,
          'duration': 300,
          'currency': 'ZAR',
          'price': '4000.00',
          'booking_notice_in_minutes': 1440,
          'reschedule_notice_in_minutes': 1440,
          'number_of_people': 1,
          'service': 31
        }]
      }],
      'clients_url': '/api/v2/practitioner/clients/',
      'sub_domain': 'guru',
      'slug': 'guru',
      'practice_name': 'AppointmentGuru',
      'description': 'Interested in learning more about [AppointmentGuru](http://appointmentguru.co)? We do demos in the Johannesburg area. You can book an appointment below.',
      'profile_picture': 'http://localhost:8000/media/practitioner/profile/profile1.jpg',
      'logo_picture': 'http://localhost:8000/media/practitioner/logo/icon_1024x1024.png',
      'background_picture': '/static/heroes/dietician/artur-rutkowski-97622_1024.jpg',
      'timezone': 'Africa/Johannesburg',
      'facebook': '',
      'twitter': '',
      'linkedin': '',
      'data': {},
      'published': true,
      'is_website_published': true,
      'is_visible_in_app': true,
      'is_test_account': false,
      'profession': {
        'id': 2,
        'name': 'AppointmentGuru Consultant'
      },
      'business': []
    },
    'first_name': 'Christo',
    'last_name': 'Crampton',
    'is_practitioner': true,
    'is_active': true,
    'is_admin': true,
    'phone_number_confirmed': false,
    'email_confirmed': false,
    'date_joined': '2016-08-22T14:12:17.205833Z',
    'last_login': '2017-04-20T13:02:09.144831Z'
  }]
}
