# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'new', b'new'), (b'sent', b'sent'), (b'paid', b'paid'), (b'unpaid', b'unpaid')], default=b'new', max_length=10)),
                ('from_id', models.CharField(blank=True, max_length=36, null=True)),
                ('to_id', models.CharField(blank=True, max_length=36, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=36, null=True)),
                ('purchase_order_number', models.CharField(blank=True, max_length=36, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('from_string', models.TextField(blank=True, null=True)),
                ('to_string', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default=b'ZAR', max_length=4, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=36, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='invoice.Invoice')),
            ],
        ),
    ]
