# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 21:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='from_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='from_string',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='purchase_order_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='to_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='to_string',
        ),
        migrations.AddField(
            model_name='invoice',
            name='context',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='object_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None),
        ),
        migrations.AddField(
            model_name='invoice',
            name='practitioner_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='template',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, default='ZAR', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('sent', 'sent'), ('paid', 'paid'), ('unpaid', 'unpaid')], default='new', max_length=10),
        ),
    ]
