# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='password',
            field=models.CharField(blank=True, default=invoice.models.get_uuid, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='template',
            field=models.CharField(blank=True, choices=[('basic', 'basic - A simple invoice template')], max_length=255, null=True),
        ),
    ]
