# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20171013_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_password',
            field=models.CharField(blank=True, default=invoice.models.get_uuid, max_length=255, null=True),
        ),
    ]
