# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20171110_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='short_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_password',
            field=models.CharField(blank=True, default=invoice.models.get_short_uuid, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='password',
            field=models.CharField(blank=True, default=invoice.models.get_short_uuid, max_length=255, null=True),
        ),
    ]
