# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20171123_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
