# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20171127_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
