# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 09:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20171205_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practitioner_id', models.CharField(db_index=True, max_length=128)),
                ('quote_notes', models.TextField(blank=True, null=True)),
                ('invoice_notes', models.TextField(blank=True, null=True)),
                ('receipt_notes', models.TextField(blank=True, null=True)),
                ('invoice_address', models.TextField(blank=True, help_text='Your address as shown on invoices', null=True)),
                ('customer_info', models.TextField(blank=True, help_text='Choose how you would like to display your customers info', null=True)),
                ('lineitem_template', models.TextField(blank=True, default='codetable.html', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='appointments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), db_index=True, default=[], size=None),
        ),
    ]
