# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_auto_20180419_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='show_snapcode_on_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='snap_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
