# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_auto_20180419_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesettings',
            name='snap_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
