# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 08:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_auto_20180419_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practitioner_id', models.CharField(db_index=True, max_length=128)),
                ('customer_id', models.CharField(db_index=True, max_length=128)),
                ('appointments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, db_index=True, default=[], null=True, size=None)),
                ('amount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('eft', 'eft'), ('cash', 'cash'), ('snapscan', 'snapscan'), ('credit_card', 'credit_card'), ('write_off', 'write_off'), ('unknown', 'unknown'), ('medicalaid', 'medicalaid'), ('gift', 'gift'), ('voucher', 'voucher')], db_index=True, max_length=128)),
                ('payment_date', models.DateTimeField(db_index=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('invoice_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='allow_pre_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='include_vat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='request_contact_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='request_medical_aid_details',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='vat_percent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
