# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_auto_20180626_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='invoice_id',
            new_name='invoice',
        ),
    ]
