# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_auto_20180626_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='billing_address',
            field=models.TextField(blank=True, help_text='The address of the billing party', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='template',
            field=models.CharField(blank=True, choices=[('basic', 'basic - A simple invoice template'), ('material', 'material - A meterial design themed invoice template')], default='basic', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='request_medical_aid_details',
            field=models.BooleanField(default=False),
        ),
    ]
