# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_invoice_request_medical_aid_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=invoice.models.proof_upload_path)),
                ('approved', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.Payment')),
            ],
        ),
    ]
