# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_proofofpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='allow_submit_to_medical_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proofofpayment',
            name='auto_submit_to_medical_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proofofpayment',
            name='medical_aid_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
