# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_auto_20180629_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='request_medical_aid_details',
            new_name='integrate_medical_aid',
        ),
        migrations.RenameField(
            model_name='invoicesettings',
            old_name='request_contact_details',
            new_name='integrate_medical_aid',
        ),
        migrations.RemoveField(
            model_name='invoicesettings',
            name='request_medical_aid_details',
        ),
        migrations.AlterField(
            model_name='proofofpayment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=invoice.models.proof_upload_path),
        ),
    ]
