# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_auto_20180704_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoicee_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
