# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_invoice_invoicee_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesettings',
            name='invoice_address',
        ),
        migrations.AddField(
            model_name='invoice',
            name='medicalaid_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='customer_info',
            field=models.TextField(blank=True, help_text='Choose how you would like to display your customers info', null=True, verbose_name='Customer info template'),
        ),
    ]
