# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0027_auto_20180712_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='integrate_medical_aid',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='allow_pre_payments',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='allow_submit_to_medical_aid',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='include_booking_info',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='include_vat',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='integrate_medical_aid',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='show_snapcode_on_invoice',
            field=models.NullBooleanField(default=False),
        ),
    ]
