# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0031_auto_20180828_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='banking_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
