example_context = {
	'date': '2018-04-25',
	'logo': '',
	'notes': '',
	'title': 'Luana Jordaan',
	'due_date': '2018-04-30',
	'from_string': 'Christo Crampton, \n64 2nd ave, \nParkhurst',
	'account_info': 'Luana Jordaan',
	'appointments': [{
		'id': 16302,
		'day': 5,
		'data': {},
		'done': False,
		'tags': None,
		'year': 2018,
		'codes': [],
		'month': 4,
		'notes': None,
		'price': '5500.00',
		'title': 'Luana Jordaan',
		'client': {
			'id': 678,
			'email': 'luana.jordaan@gmail.com',
			'title': None,
			'initials': None,
			'is_admin': False,
			'is_active': True,
			'last_name': 'Jordaan',
			'first_name': 'Luana',
			'last_login': '2017-04-28T09:36:18.419314Z',
			'date_joined': '2017-04-28T09:36:18.419204Z',
			'phone_number': '+27823201039',
			'email_confirmed': False,
			'is_practitioner': False,
			'phone_number_confirmed': False
		},
		'source': 'app.v2.web',
		'status': 'N',
		'process': [],
		'product': 88,
		'currency': 'ZAR',
		'end_time': '2018-04-05T16:00:00Z',
		'location': {},
		'full_name': 'Luana Jordaan',
		'start_time': '2018-04-05T07:00:00Z',
		'amount_paid': '0.00',
		'invoiceable': True,
		'created_date': '2018-04-03T08:13:08.997732Z',
		'paid_in_full': False,
		'practitioner': {
			'id': 1,
			'email': 'christo@appointmentguru.co',
			'profile': {
				'data': {},
				'slug': 'guru',
				'tags': None,
				'user': 1,
				'twitter': '',
				'business': [],
				'currency': 'ZAR',
				'facebook': 'https://www.facebook.com/appointmentguru/',
				'linkedin': '',
				'timezone': 'Africa/Johannesburg',
				'instagram': '',
				'published': True,
				'profession': {
					'id': 2,
					'name': 'AppointmentGuru Consultant'
				},
				'sub_domain': 'guru',
				'clients_url': '/api/v2/practitioner/clients/',
				'description': 'Interested in learning more about [AppointmentGuru](http://appointmentguru.co)? We do demos in the Johannesburg area. You can book an appointment below.',
				'logo_picture': 'https://media-appointmentguru.s3.amazonaws.com:443/practitioner/images/1/logo.png',
				'practice_name': '',
				'banking_details': 'Christopher Crampton. \r\nFNB. \r\nAccount number: 60232195566',
				'is_test_account': False,
				'practice_number': '',
				'profile_picture': 'https://media-appointmentguru.s3.amazonaws.com:443/practitioner/images/1/profile.jpg',
				'is_visible_in_app': True,
				'background_picture': '//images.unsplash.com/photo-1453928582365-b6ad33cbcf64?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjExOTkxfQ&s=91d6ef7d248f9bbb73bb41cd1e0ce248',
				'is_website_published': True,
				'free_trial_expiry_date': None
			},
			'username': 'christo@appointmentguru.co',
			'last_name': 'Crampton',
			'first_name': 'Christo',
			'last_login': '2018-04-08T12:27:11.391560Z',
			'date_joined': '2016-08-22T14:12:17.205833Z',
			'phone_number': '+27832566533',
			'is_practitioner': True
		},
		'contact_email': 'luana.jordaan@gmail.com',
		'contact_phone': '+27823201039',
		'invoice_title': 'Full day consultation. Thu 05 Apr 2018',
		'modified_date': '2018-04-19T12:14:48.896440Z',
		'create_process': False,
		'editable_by_client': True,
		'invoice_description': None,
		'recurring_appointment': None
	}, {
		'id': 16867,
		'day': 11,
		'data': {},
		'done': False,
		'tags': None,
		'year': 2018,
		'codes': [],
		'month': 4,
		'notes': None,
		'price': '5500.00',
		'title': 'Luana Jordaan',
		'client': {
			'id': 678,
			'email': 'luana.jordaan@gmail.com',
			'title': None,
			'initials': None,
			'is_admin': False,
			'is_active': True,
			'last_name': 'Jordaan',
			'first_name': 'Luana',
			'last_login': '2017-04-28T09:36:18.419314Z',
			'date_joined': '2017-04-28T09:36:18.419204Z',
			'phone_number': '+27823201039',
			'email_confirmed': False,
			'is_practitioner': False,
			'phone_number_confirmed': False
		},
		'source': 'app.v2.web',
		'status': 'N',
		'process': [],
		'product': 88,
		'currency': 'ZAR',
		'end_time': '2018-04-11T16:00:00Z',
		'location': {},
		'full_name': 'Luana Jordaan',
		'start_time': '2018-04-11T07:00:00Z',
		'amount_paid': '0.00',
		'invoiceable': True,
		'created_date': '2018-04-10T06:00:31.076427Z',
		'paid_in_full': False,
		'practitioner': {
			'id': 1,
			'email': 'christo@appointmentguru.co',
			'profile': {
				'data': {},
				'slug': 'guru',
				'tags': None,
				'user': 1,
				'twitter': '',
				'business': [],
				'currency': 'ZAR',
				'facebook': 'https://www.facebook.com/appointmentguru/',
				'linkedin': '',
				'timezone': 'Africa/Johannesburg',
				'instagram': '',
				'published': True,
				'profession': {
					'id': 2,
					'name': 'AppointmentGuru Consultant'
				},
				'sub_domain': 'guru',
				'clients_url': '/api/v2/practitioner/clients/',
				'description': 'Interested in learning more about [AppointmentGuru](http://appointmentguru.co)? We do demos in the Johannesburg area. You can book an appointment below.',
				'logo_picture': 'https://media-appointmentguru.s3.amazonaws.com:443/practitioner/images/1/logo.png',
				'practice_name': '',
				'banking_details': 'Christopher Crampton. \r\nFNB. \r\nAccount number: 60232195566',
				'is_test_account': False,
				'practice_number': '',
				'profile_picture': 'https://media-appointmentguru.s3.amazonaws.com:443/practitioner/images/1/profile.jpg',
				'is_visible_in_app': True,
				'background_picture': '//images.unsplash.com/photo-1453928582365-b6ad33cbcf64?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjExOTkxfQ&s=91d6ef7d248f9bbb73bb41cd1e0ce248',
				'is_website_published': True,
				'free_trial_expiry_date': None
			},
			'username': 'christo@appointmentguru.co',
			'last_name': 'Crampton',
			'first_name': 'Christo',
			'last_login': '2018-04-08T12:27:11.391560Z',
			'date_joined': '2016-08-22T14:12:17.205833Z',
			'phone_number': '+27832566533',
			'is_practitioner': True
		},
		'contact_email': 'luana.jordaan@gmail.com',
		'contact_phone': '+27823201039',
		'invoice_title': 'Full day consultation. Wed 11 Apr 2018',
		'modified_date': '2018-04-19T12:15:01.412745Z',
		'create_process': False,
		'editable_by_client': True,
		'invoice_description': None,
		'recurring_appointment': None
	}, {
		'id': 17276,
		'day': 20,
		'data': {},
		'done': False,
		'tags': None,
		'year': 2018,
		'codes': [],
		'month': 4,
		'notes': None,
		'price': '5500.00',
		'title': 'Luana Jordaan',
		'client': {
			'id': 678,
			'email': 'luana.jordaan@gmail.com',
			'title': None,
			'initials': None,
			'is_admin': False,
			'is_active': True,
			'last_name': 'Jordaan',
			'first_name': 'Luana',
			'last_login': '2017-04-28T09:36:18.419314Z',
			'date_joined': '2017-04-28T09:36:18.419204Z',
			'phone_number': '+27823201039',
			'email_confirmed': False,
			'is_practitioner': False,
			'phone_number_confirmed': False
		},
		'source': 'app.v2.web',
		'status': 'N',
		'process': [],
		'product': 88,
		'currency': 'ZAR',
		'end_time': '2018-04-20T16:00:00Z',
		'location': {},
		'full_name': 'Luana Jordaan',
		'start_time': '2018-04-20T07:00:00Z',
		'amount_paid': '0.00',
		'invoiceable': True,
		'created_date': '2018-04-19T09:23:55.673455Z',
		'paid_in_full': False,
		'practitioner': {
			'id': 1,
			'email': 'christo@appointmentguru.co',
			'profile': {
				'data': {},
				'slug': 'guru',
				'tags': None,
				'user': 1,
				'twitter': '',
				'business': [],
				'currency': 'ZAR',
				'facebook': 'https://www.facebook.com/appointmentguru/',
				'linkedin': '',
				'timezone': 'Africa/Johannesburg',
				'instagram': '',
				'published': True,
				'profession': {
					'id': 2,
					'name': 'AppointmentGuru Consultant'
				},
				'sub_domain': 'guru',
				'clients_url': '/api/v2/practitioner/clients/',
				'description': 'Interested in learning more about [AppointmentGuru](http://appointmentguru.co)? We do demos in the Johannesburg area. You can book an appointment below.',
				'logo_picture': 'https://media-appointmentguru.s3.amazonaws.com:443/practitioner/images/1/logo.png',
				'practice_name': '',
				'banking_details': 'Christopher Crampton. \r\nFNB. \r\nAccount number: 60232195566',
				'is_test_account': False,
				'practice_number': '',
				'profile_picture': 'https://media-appointmentguru.s3.amazonaws.com:443/practitioner/images/1/profile.jpg',
				'is_visible_in_app': True,
				'background_picture': '//images.unsplash.com/photo-1453928582365-b6ad33cbcf64?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjExOTkxfQ&s=91d6ef7d248f9bbb73bb41cd1e0ce248',
				'is_website_published': True,
				'free_trial_expiry_date': None
			},
			'username': 'christo@appointmentguru.co',
			'last_name': 'Crampton',
			'first_name': 'Christo',
			'last_login': '2018-04-08T12:27:11.391560Z',
			'date_joined': '2016-08-22T14:12:17.205833Z',
			'phone_number': '+27832566533',
			'is_practitioner': True
		},
		'contact_email': 'luana.jordaan@gmail.com',
		'contact_phone': '+27823201039',
		'invoice_title': 'Full day consultation. Fri 20 Apr 2018',
		'modified_date': '2018-04-19T12:15:14.085850Z',
		'create_process': False,
		'editable_by_client': True,
		'invoice_description': None,
		'recurring_appointment': None
	}],
	'patient_info': None,
	'sender_email': 'christo@appointmentguru.co',
	'customer_info': 'Vumatel (Pty) Ltd \nVAT reg: 4020266740 \nPO Box 1811 \nParklands \n2121',
	'invoice_total': 0,
	'practice_name': '',
	'banking_details': 'Christopher Crampton. \r\nFNB. \r\nAccount number: 60232195566',
	'medicalaid_info': None,
	'practice_number': '',
	'practitioner_id': 1,
	'invoice_period_to': '2018-04-25',
	'invoice_period_from': '2018-04-01'
}